# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpcCalc_pb2 as grpcCalc__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpcCalc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class apiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add = channel.unary_unary(
                '/main.api/add',
                request_serializer=grpcCalc__pb2.args.SerializeToString,
                response_deserializer=grpcCalc__pb2.result.FromString,
                _registered_method=True)
        self.sub = channel.unary_unary(
                '/main.api/sub',
                request_serializer=grpcCalc__pb2.args.SerializeToString,
                response_deserializer=grpcCalc__pb2.result.FromString,
                _registered_method=True)
        self.mult = channel.unary_unary(
                '/main.api/mult',
                request_serializer=grpcCalc__pb2.args.SerializeToString,
                response_deserializer=grpcCalc__pb2.result.FromString,
                _registered_method=True)
        self.div = channel.unary_unary(
                '/main.api/div',
                request_serializer=grpcCalc__pb2.args.SerializeToString,
                response_deserializer=grpcCalc__pb2.result.FromString,
                _registered_method=True)


class apiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def mult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def div(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_apiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add': grpc.unary_unary_rpc_method_handler(
                    servicer.add,
                    request_deserializer=grpcCalc__pb2.args.FromString,
                    response_serializer=grpcCalc__pb2.result.SerializeToString,
            ),
            'sub': grpc.unary_unary_rpc_method_handler(
                    servicer.sub,
                    request_deserializer=grpcCalc__pb2.args.FromString,
                    response_serializer=grpcCalc__pb2.result.SerializeToString,
            ),
            'mult': grpc.unary_unary_rpc_method_handler(
                    servicer.mult,
                    request_deserializer=grpcCalc__pb2.args.FromString,
                    response_serializer=grpcCalc__pb2.result.SerializeToString,
            ),
            'div': grpc.unary_unary_rpc_method_handler(
                    servicer.div,
                    request_deserializer=grpcCalc__pb2.args.FromString,
                    response_serializer=grpcCalc__pb2.result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.api', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('main.api', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class api(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.api/add',
            grpcCalc__pb2.args.SerializeToString,
            grpcCalc__pb2.result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.api/sub',
            grpcCalc__pb2.args.SerializeToString,
            grpcCalc__pb2.result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def mult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.api/mult',
            grpcCalc__pb2.args.SerializeToString,
            grpcCalc__pb2.result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def div(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.api/div',
            grpcCalc__pb2.args.SerializeToString,
            grpcCalc__pb2.result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
