# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpcCalc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpcCalc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egrpcCalc.proto\x12\x04main\"\x15\n\x06result\x12\x0b\n\x03num\x18\x01 \x01(\x05\"&\n\x04\x61rgs\x12\x0e\n\x06numOne\x18\x01 \x01(\x05\x12\x0e\n\x06numTwo\x18\x02 \x01(\x05\x32\x8a\x01\n\x03\x61pi\x12\x1f\n\x03\x61\x64\x64\x12\n.main.args\x1a\x0c.main.result\x12\x1f\n\x03sub\x12\n.main.args\x1a\x0c.main.result\x12 \n\x04mult\x12\n.main.args\x1a\x0c.main.result\x12\x1f\n\x03\x64iv\x12\n.main.args\x1a\x0c.main.resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpcCalc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESULT']._serialized_start=24
  _globals['_RESULT']._serialized_end=45
  _globals['_ARGS']._serialized_start=47
  _globals['_ARGS']._serialized_end=85
  _globals['_API']._serialized_start=88
  _globals['_API']._serialized_end=226
# @@protoc_insertion_point(module_scope)
