# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import miner_pb2 as miner__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in miner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class apiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getTransactionID = channel.unary_unary(
                '/main.api/getTransactionID',
                request_serializer=miner__pb2.Void.SerializeToString,
                response_deserializer=miner__pb2.IntegerResponse.FromString,
                _registered_method=True)
        self.getChallenge = channel.unary_unary(
                '/main.api/getChallenge',
                request_serializer=miner__pb2.TransactionID.SerializeToString,
                response_deserializer=miner__pb2.IntegerResponse.FromString,
                _registered_method=True)
        self.getTransactionStatus = channel.unary_unary(
                '/main.api/getTransactionStatus',
                request_serializer=miner__pb2.TransactionID.SerializeToString,
                response_deserializer=miner__pb2.IntegerResponse.FromString,
                _registered_method=True)
        self.submitChallenge = channel.unary_unary(
                '/main.api/submitChallenge',
                request_serializer=miner__pb2.ChallengeArgs.SerializeToString,
                response_deserializer=miner__pb2.IntegerResponse.FromString,
                _registered_method=True)
        self.getWinner = channel.unary_unary(
                '/main.api/getWinner',
                request_serializer=miner__pb2.TransactionID.SerializeToString,
                response_deserializer=miner__pb2.IntegerResponse.FromString,
                _registered_method=True)
        self.getSolution = channel.unary_unary(
                '/main.api/getSolution',
                request_serializer=miner__pb2.TransactionID.SerializeToString,
                response_deserializer=miner__pb2.SolutionData.FromString,
                _registered_method=True)


class apiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getTransactionID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getChallenge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTransactionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def submitChallenge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getWinner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSolution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_apiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getTransactionID': grpc.unary_unary_rpc_method_handler(
                    servicer.getTransactionID,
                    request_deserializer=miner__pb2.Void.FromString,
                    response_serializer=miner__pb2.IntegerResponse.SerializeToString,
            ),
            'getChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.getChallenge,
                    request_deserializer=miner__pb2.TransactionID.FromString,
                    response_serializer=miner__pb2.IntegerResponse.SerializeToString,
            ),
            'getTransactionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.getTransactionStatus,
                    request_deserializer=miner__pb2.TransactionID.FromString,
                    response_serializer=miner__pb2.IntegerResponse.SerializeToString,
            ),
            'submitChallenge': grpc.unary_unary_rpc_method_handler(
                    servicer.submitChallenge,
                    request_deserializer=miner__pb2.ChallengeArgs.FromString,
                    response_serializer=miner__pb2.IntegerResponse.SerializeToString,
            ),
            'getWinner': grpc.unary_unary_rpc_method_handler(
                    servicer.getWinner,
                    request_deserializer=miner__pb2.TransactionID.FromString,
                    response_serializer=miner__pb2.IntegerResponse.SerializeToString,
            ),
            'getSolution': grpc.unary_unary_rpc_method_handler(
                    servicer.getSolution,
                    request_deserializer=miner__pb2.TransactionID.FromString,
                    response_serializer=miner__pb2.SolutionData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.api', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('main.api', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class api(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getTransactionID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.api/getTransactionID',
            miner__pb2.Void.SerializeToString,
            miner__pb2.IntegerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.api/getChallenge',
            miner__pb2.TransactionID.SerializeToString,
            miner__pb2.IntegerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getTransactionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.api/getTransactionStatus',
            miner__pb2.TransactionID.SerializeToString,
            miner__pb2.IntegerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def submitChallenge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.api/submitChallenge',
            miner__pb2.ChallengeArgs.SerializeToString,
            miner__pb2.IntegerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getWinner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.api/getWinner',
            miner__pb2.TransactionID.SerializeToString,
            miner__pb2.IntegerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSolution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/main.api/getSolution',
            miner__pb2.TransactionID.SerializeToString,
            miner__pb2.SolutionData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
