# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: miner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'miner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bminer.proto\x12\x04main\" \n\x0fIntegerResponse\x12\r\n\x05value\x18\x01 \x01(\x05\"C\n\x0cSolutionData\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x10\n\x08solution\x18\x02 \x01(\t\x12\x11\n\tchallenge\x18\x03 \x01(\x05\"&\n\rTransactionID\x12\x15\n\rtransactionId\x18\x01 \x01(\x05\"J\n\rChallengeArgs\x12\x15\n\rtransactionId\x18\x01 \x01(\x05\x12\x10\n\x08\x63lientId\x18\x02 \x01(\x05\x12\x10\n\x08solution\x18\x03 \x01(\t\"\x06\n\x04Void2\xec\x02\n\x03\x61pi\x12\x35\n\x10getTransactionID\x12\n.main.Void\x1a\x15.main.IntegerResponse\x12:\n\x0cgetChallenge\x12\x13.main.TransactionID\x1a\x15.main.IntegerResponse\x12\x42\n\x14getTransactionStatus\x12\x13.main.TransactionID\x1a\x15.main.IntegerResponse\x12=\n\x0fsubmitChallenge\x12\x13.main.ChallengeArgs\x1a\x15.main.IntegerResponse\x12\x37\n\tgetWinner\x12\x13.main.TransactionID\x1a\x15.main.IntegerResponse\x12\x36\n\x0bgetSolution\x12\x13.main.TransactionID\x1a\x12.main.SolutionDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'miner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTEGERRESPONSE']._serialized_start=21
  _globals['_INTEGERRESPONSE']._serialized_end=53
  _globals['_SOLUTIONDATA']._serialized_start=55
  _globals['_SOLUTIONDATA']._serialized_end=122
  _globals['_TRANSACTIONID']._serialized_start=124
  _globals['_TRANSACTIONID']._serialized_end=162
  _globals['_CHALLENGEARGS']._serialized_start=164
  _globals['_CHALLENGEARGS']._serialized_end=238
  _globals['_VOID']._serialized_start=240
  _globals['_VOID']._serialized_end=246
  _globals['_API']._serialized_start=249
  _globals['_API']._serialized_end=613
# @@protoc_insertion_point(module_scope)
